name: data_structure_and_algorithm
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  collection: ^1.18.0
  uuid: ^4.4.2
  json_annotation: ^4.9.0


dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  lints: ^2.0.0
  test: ^1.21.0
  
